### PR TITLE
Refactored test/citation-test script

### PR DESCRIPTION
**Pull request by briri**
Hey @jupiter007 your script looked good. I refactored it a bit.

The primary changes were to add the `dmproadmap_related_identifiers` array to the initial query and then only do a full fetch of the DMP record if we need to update it.

I ran against the dev DB and all looks good. When you're back, we can run against stage

### CODE REVIEW

**Review by jupiter007 — APPROVED** [review]

**Comment by jupiter007** [comment]
Thanks Brian.

**Comment by jupiter007** [comment]
Hi @briri. Per your suggestion, I ran your script for stage, and there were only three DMPs that appeared to be missing citations. I checked DynamoDB, and it appears to have inserted the missing citations for the following:
DMP#doi.org/10.48321/D132DC0f6f
DMP#doi.org/10.48321/D17P5X
DMP#doi.org/10.48321/D14A42200F

When I ran it a second time, there were no more identified, indicating that the script fixed the issue for Stage.

**Comment by briri** [comment]
Excellent! I will go ahead an merge then.

**Comment by briri** [comment]
Do you want to do a PR to main and run the script in prd?

**Comment by jupiter007** [comment]
> Do you want to do a PR to main and run the script in prd?

Thanks Brian. Yes, I will go ahead and create a PR and run it against production.

**Pull request merged**
